### ISSUE TITLE
LoadProfile()

### ISSUE THREAD

**Issue by chowa3** [Emotiv/unity-plugin#14]
I have created a Unity Project and imported the Unity Plugin from the Emotiv Github page. The LoadProfile() function does not Load a Profile. Instead it returns the error, "NullReferenceException: Object reference not set to an instance of an object."  My C# script is attached and a picture of the console with the associated errors.
![LoadProfile](https://user-images.githubusercontent.com/74928750/151198203-84f5c486-84f0-4472-9eef-8f6b714468cc.JPG)

![Test Script](https://user-images.githubusercontent.com/74928750/151198506-f916dd20-3a90-4bcc-b418-e3011fd04f0b.JPG)

**Comment by tungntEmotiv** [comment]
Hi @chowa3 ,

Sorry for late response. I think the exception because the _profileLists might be null at LoadProfile() and UnLoadProfile(). In BCITraining.cs , we initialize the _profileLists by null then update it at  at queryProfile response. So you should call queryProfile before call loadProfile() in your example.
Thanks for your issue raising, i think we should initialize _profileLists  with empty List<string> instead of null to avoid this issue.

**Comment by chowa3** [comment]
Thank you for the response! @tungntEmotiv I have been running QueryProfile() first. However, I just noticed that the list of profiles is no longer being returned to the console. Do you know why QueryProfile() (line 37 above) wouldn't be sending the response?

**Comment by tungntEmotiv** [comment]
Can i check via teamviewer? my email is tungnguyen@emotiv.com

**Comment by chowa3** [comment]
Yes, thank you! I've sent you an email.
